ARG VERSION=3.8
FROM python:${VERSION}-bookworm

COPY requirements.txt requirements-dev.txt /tmp/

# when testing a new version of the github datatrails-python repo copy the wheel
# (generated by 'task wheel') from that repo and uncomment
# the following lines. Also comment out the datatrails-archivist line in
# requirements.txt.
# cp ~/git/datatrails-python/dist/*.whl .
# That way one can test an unreleased version of github datatrails-samples.
# NB dont forget to recomment before merging !!
# COPY datatrails*.whl /tmp/
# RUN python3 -m pip -qq install /tmp/datatrails*.whl \
#   && rm -f /tmp/datatrails*.whl

RUN python3 -m pip -qq install --upgrade pip \
  && python3 -m pip -qq install -r /tmp/requirements-dev.txt \
  && rm -f /tmp/requirements-dev.txt \
  && rm -f /tmp/requirements.txt

ENV USER=api
ENV HOME=/home/${USER}
RUN mkdir -p ${HOME}
ENV PYTHONPATH=${HOME}/samples
ENV PATH=${HOME}/.local/bin:${PATH}
WORKDIR ${HOME}
