version: '3'

tasks:

  about:
    desc: Generate about.py
    cmds:
      - ./scripts/api.sh ./scripts/version.sh
    status:
      - test -s archivist/about.py

  api:
    desc: Build a docker environment with the right dependencies and utilities
    cmds:
      - docker build --no-cache --build-arg VERSION=3.7 -f Dockerfile -t jitsuin-samples-api .

  api-3.8:
    desc: Build a docker environment with the right dependencies and utilities
    cmds:
      - docker build --no-cache --build-arg VERSION=3.8 -f Dockerfile -t jitsuin-samples-api .
  
  api-3.9:
    desc: Build a docker environment with the right dependencies and utilities
    cmds:
      - docker build --no-cache --build-arg VERSION=3.9 -f Dockerfile -t jitsuin-samples-api .
  
  api-3.10:
    desc: Build a docker environment with the right dependencies and utilities
    cmds:
      - docker build --no-cache --build-arg VERSION=3.10 -f Dockerfile -t jitsuin-samples-api .

  api-3.11:
    desc: Build a docker environment with the right dependencies and utilities
    cmds:
      - docker build --no-cache --build-arg VERSION=3.11 -f Dockerfile -t jitsuin-samples-api .

  check:
    desc: Check the style, bug and quality of the code
    deps: [about]
    cmds:
      - ./scripts/api.sh python3 --version
      - ./scripts/api.sh pycodestyle --format=pylint archivist_samples
      - ./scripts/api.sh python3 -m pylint archivist_samples

  clean:
    desc: Clean git repo
    cmds:
      - git clean -fdX

  format:
    desc: Format code using black
    deps: [about]
    cmds: 
      - ./scripts/api.sh black archivist_samples

  functests:
    desc: Run samples tests in virtual env using local wheel package - local wheel must be present
    cmds:
      - ./scripts/functests.sh

  publish:
    desc: publish wheel package (will require username and password in TWINE_USERNAME,TWINE_PASSWORD)
    deps: [about]
    cmds:
      - ./scripts/api.sh python3 -m twine check dist/*
      - ./scripts/api.sh python3 -m twine upload --verbose --repository pypi dist/*

  samples:
    desc: Run samples tests
    deps: [about]
    cmds:
      - ./scripts/api.sh ./scripts/samples.sh

  wheel:
    desc: Builds python wheel package
    deps: [about, clean]
    cmds:
      - ./scripts/api.sh ./scripts/wheel.sh
